### PR TITLE
MassTransit-related fixes

### LINKED ISSUE #106: Inbox/outbox cleaners fail if there is no schema
If there is no schema set on inbox/outbox entities, the cleaners with fail. The reason is that table name generated by `DbContextExtensions.GetFullTableName` will return sth like this `[].[ConsumedMessages]`

### PR DESCRIPTION
**Pull request by jakubfijalkowski**
Fixes #106 and #169 .

Plus some small fixes (NRT-related) and one package change.

### CODE REVIEW

File: src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/NewtonsoftJsonEventsSerializer.cs [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+            return JsonConvert.DeserializeObject(evt.Payload, type, settings)!;
+        }
+
+        private Type GetEventType(string type)
+        {
+            return typesCatalog.Assemblies
+                .Select(ass => ass.GetType(type))
+                .Where(t => t != null)
+                .FirstOrDefault()
+                ?? throw new InvalidOperationException($"Type: {type} is not defined in any of contract assemblies");
```
Comment (Saancreed) [inline src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/NewtonsoftJsonEventsSerializer.cs]: Just `First` would be descriptive enough I think.

File: src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/NewtonsoftJsonEventsSerializer.cs [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+        private readonly JsonSerializerSettings settings;
+
+        public NewtonsoftJsonEventsSerializer(TypesCatalog typesCatalog)
+            : this(typesCatalog, null)
+        { }
+
+        public NewtonsoftJsonEventsSerializer(TypesCatalog typesCatalog, JsonSerializerSettings? settings)
+        {
+            this.typesCatalog = typesCatalog;
+            this.settings = settings ?? new JsonSerializerSettings
```
Comment (Saancreed) [inline src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/NewtonsoftJsonEventsSerializer.cs]: Type can be omitted, unless you want to keep it for clarity.

File: src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/SystemTextJsonEventsSerializer.cs [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+using System.Text.Json;
+using LeanCode.Components;
+
+namespace LeanCode.DomainModels.MassTransitRelay.Outbox
+{
+    /// <remarks>
+    /// This is not usable yet. `System.Text.Json` does not support private constructors and requires
+    /// users to add `JsonIncludeAttribute` to properties with private setters.
+    /// More info: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-5-0
+    /// TODO: try to fix in .NET 6
```
Comment (Saancreed) [inline src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/SystemTextJsonEventsSerializer.cs:13]: :disappointed:

File: src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/SystemTextJsonEventsSerializer.cs [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+            return JsonSerializer.Serialize(evt, options);
+        }
+
+        private Type GetEventType(string type)
+        {
+            return typesCatalog.Assemblies
+                .Select(ass => ass.GetType(type))
+                .Where(t => t != null)
+                .FirstOrDefault()
+                ?? throw new InvalidOperationException($"Type: {type} is not defined in any of contract assemblies");
```
Comment (Saancreed) [inline src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/SystemTextJsonEventsSerializer.cs]: Same as in the other one.

**Review by lukaszgarstecki — APPROVED** [review]

File: test/Domain/LeanCode.DomainModels.MassTransitRelay.Tests/JsonEventsSerializerTests.cs [hunk 5]
```diff
@@ -46,25 +45,78 @@ public void Deserializes_event()
...
+        {
+            var evt = TestEventWithPrivateFields.Create("test value");
+
+            var wrapped = Serializer.WrapEvent(evt, CorrelationId);
+            var unwrapped = Serializer.ExtractEvent(wrapped);
+
+            Assert.Equal(evt, unwrapped);
+        }
+
+        public record TestEvent : IDomainEvent
```
Comment (Saancreed) [inline test/Domain/LeanCode.DomainModels.MassTransitRelay.Tests/JsonEventsSerializerTests.cs]: I think for tests it would be acceptable to use positional records here.

**Review by Saancreed — APPROVED** [review]

File: src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/NewtonsoftJsonEventsSerializer.cs (hunk 1 above)
Comment (jakubfijalkowski) [reply src/Domain/LeanCode.DomainModels.MassTransitRelay/Outbox/NewtonsoftJsonEventsSerializer.cs]: Considering that it might be thrown in apps and it will be raised from the depths of processing pipeline, I think that as much additional info as possible is better. `First` will throw a very generic error and sometimes stack trace might not be available (logs).

**Review by Dragemil — APPROVED** [review]

**Review by marcin-dardzinski — APPROVED** [review]
